name: Fireflies to Google Drive Automation

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  process-transcripts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run Fireflies automation
      env:
        FIREFLIES_API_KEY: ${{ secrets.FIREFLIES_API_KEY }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        LOOKBACK_HOURS: 1
      run: |
        # Use cloud-compatible version
        node cloud-index.js
        
    - name: Upload results to Google Drive
      if: always()
      run: |
        echo "Automation completed at $(date)"